# Generated by Django 4.0 on 2024-05-26 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='conductivity',
            field=models.FloatField(default=45.0),
        ),
        migrations.AddField(
            model_name='animal',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='volume',
            field=models.FloatField(default=45.0),
        ),
    ]
